### ISSUE TITLE
NoDamI doesn't work with First Aid

### ISSUE THREAD

**Issue by boniblade** [ProfHugo/NoDamI#15]
With NoDamI and First Aid installed, I was getting shot by alot of things
Noticed I wasn't getting hit enough, so I went into a creative world to test
After removing mods and combining them, I found out it was First Aid doing it
Please fix, I want my bones broken rapidly!

**Comment by ProfHugo** [comment]
Latest patch should fix it. I've done some testing myself and it seems fine. Please let me know if you run into any problems. I'll close it for now.
