### ISSUE TITLE
Damage Source Whitelist not working

### ISSUE THREAD

**Issue by Luke616** [ProfHugo/NoDamI#4]
Hello,

I love how NoDamI makes faster, lower-damage weapons viable. However, for my personal tastes I'd like to force some damage sources (such as IE wire or magma blocks) to respect damage immunity. Unfortunately, I can't seem to get the dmgSrcWhitelist to work properly - wondering if there is a bug here?

Screenshot of my NoDamI config. The sources circled in red are not giving i-frames in game
![image](https://user-images.githubusercontent.com/3951604/53118062-45eb9680-351a-11e9-9315-f361997f1402.png)

Testing with IE razor wire
![2019-02-20_14 11 33](https://user-images.githubusercontent.com/3951604/53117931-002ece00-351a-11e9-97e1-af900ddb6025.png)

As the razor wire is not giving i-frames, I die instantly. Here is debug mode telling me the damage source, confirming that it is the same as what I entered in the configs
![2019-02-20_14 11 49](https://user-images.githubusercontent.com/3951604/53117936-01f89180-351a-11e9-8d58-568880cd4444.png)

Versions:
minecraft 1.12.2
nodami 1.2
forge 14.23.5.2808

Thanks for your time! Please let me know if you need any additional information.
- Luke

**Comment by ProfHugo** [comment]
Hello, sorry for the late response. I tested it myself with Immersive Engineering's wires, and the whitelist does work for me. Can you send me a copy of your config file? It could be due to invisible spaces/newline characters (my if statement checks if the names are exact so spaces would throw it off).

**Comment by Khioni** [comment]
@ProfHugo - I have been able to get it to work just fine, no glitches here; no end spaces or extra new lines.
I think it might be a case of extra spaces throwing things off, since the screenclip doesn't seem to show any excessive blank lines, but it could have already been fixed with **v1.2.1**

**Comment by ProfHugo** [comment]
I'll be closing this for now.
