### ISSUE TITLE
question about i-frames

### ISSUE THREAD

**Issue by SFort** [ProfHugo/NoDamI#8]
The i-frames that are given by this mod,
do they act like vanilla i-frames where nothing can damage you?
or do they only protect you from the same type of damage.
if their vanilla ones would you consider making the i-frames apply only when the damage source is of the same type?

**Comment by ProfHugo** [comment]
This mod changes how vanilla i-frames are applied (default: none), and does not implement any sort of i-frame system on its own. However, there is a system in place which would cancel player attacks if they're below a certain threshold (customizable with config). 

The initial goal of this mod is to completely remove i-frames in the first place to allow more damage from rapid hit weapons (like guns and a barrage of arrows) and multi entity combat (like being ganged up on by 4 zombies) to go through, while adding countermeasures to not competely destroy game balance, so I don't have any plans to make an exclusion for same damage type.

**Comment by SFort** [comment]
Well the reason why I ask is because within combat there are moded and vanilla damage types that would instantly kill you if there ware no i-frames but still semi defeat the idea of the mod.
Making i-frames only negate damage of the same type would fix that. 
e.g.
Fire damage is set to have i-frames by default
so in a situation where you are being ganged up on, you would actually have a advantage if you ware on fire.
But if when you recieve fire damage the i-frame only protects against fire damage the issue would not exist.

(i get if that is too mutch work tho, still great mod thanks for making it :+1: )

**Comment by Khioni** [comment]
> Fire damage is set to have i-frames by default
so in a situation where you are being ganged up on, you would actually have a advantage if you ware on fire.
But if when you recieve fire damage the i-frame only protects against fire damage the issue would not exist.

`inFire` (direct contact) and `onFire` (burning) are separate things, and fireballs are separate as well.
Being on fire wouldn't give you intermittent IFrames, and you can definitely get triple hitted by a single blaze.

Things like hugging a cactus, and standing in fire, could lead to an advantage, though.

It would be amazing if it were possible to make attacks completely bypass IFrames, so you can't dodge gangs by hugging a cactus, and even make different sources have separate IFrames, but I wouldn't expect a complete redo of them to fix that to happen in the near future.
