### ISSUE TITLE
(Compatibility) Crash with Electrobob's Wizardry minions

### ISSUE THREAD

**Issue by Cre8or** [ProfHugo/NoDamI#9]
Hello there!

I encountered an issue when playing with both **NoDamI** (v1.2.1 for MC 1.12.2) and [**Electrobob's Wizardry**](https://minecraft.curseforge.com/projects/electroblobs-wizardry) installed. Specifically, after summoning a helper minion from the Wizardry mod (e.g. a zombie or a skeleton), and attacking it (to make it turn against me), my game crashes as soon as I take damage from it. Hurting the mob is fine, but getting attacked by one causes the crash. This behaviour doesn't occur with vanilla zombies and skeletons.

This is my mod list...
```OptiFine_1.12.2_HD_U_E3.jar
VanillaFix-1.0.10-99.jar
Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar
jei_1.12.2-4.15.0.279.jar
nodami-1.12.2-1.2.1.jar
OptiFine_1.12.2_HD_U_E3.jar
```

[...and this is my crashlog.](https://github.com/ProfHugo/NoDamI/files/3183666/crash-2019-05-15_19.09.44-server.txt)

If you need any additional information, let me know!

**Edit 1:** I forgot to add Optifine in the mod list, woops.

**Edit 2:** Forgot to specify which version of NoDamI I was using. Double-woops.

**Comment by Cre8or** [comment]
Any update on this? 🙁

**Comment by ProfHugo** [comment]
Line 30 is part of the debug feature, and it looks like I forgot to add a null check to account for when the source of damage doesn't have a key entry inside Minecraft's EntityList. I'll add this to the list of stuff I need to fix for the next update, but for now just turn off the debug feature inside the config file and it should be fine.

**Comment by Cre8or** [comment]
Oh, derp. Glad to hear it's a simple fix.

Cheers!
